package imitationmgjava;

/**
 *
 * @author stathis
 */
public class MGJFrame extends javax.swing.JFrame {

    /**
     * Creates new form MGJFrame
     */
    public MGJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Seed = new javax.swing.JTextField();
        NumberOfPopulations = new javax.swing.JTextField();
        NumberOfAgents = new javax.swing.JTextField();
        NumberOfAgentsInPlay = new javax.swing.JTextField();
        NumberOfImitators = new javax.swing.JTextField();
        ImitationRounds = new javax.swing.JTextField();
        NumberOfRounds = new javax.swing.JTextField();
        ProbabilityChangeFactor = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        NumberOfRuns = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Seed.setText("0");
        Seed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SeedActionPerformed(evt);
            }
        });

        NumberOfPopulations.setText("1");

        NumberOfAgents.setText("99");

        NumberOfAgentsInPlay.setText("99");
        NumberOfAgentsInPlay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NumberOfAgentsInPlayActionPerformed(evt);
            }
        });

        NumberOfImitators.setText("3");

        ImitationRounds.setText("3");

        NumberOfRounds.setText("10000");

        ProbabilityChangeFactor.setText("0.7");

        jLabel1.setText("Seed");

        jLabel2.setText("Number of Populations");

        jLabel3.setText("Number of Agents");

        jLabel4.setText("Num. of Agents in Play");

        jLabel5.setText("Number Of Imitators");

        jLabel6.setText("Imitation Rounds");

        jLabel7.setText("Num. of Max Rounds");

        jLabel8.setText("Prob Change Factor");

        jButton1.setText("Go");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Exit");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        NumberOfRuns.setText("10");

        jLabel9.setText("Num. of Runs");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel5)
                                .addComponent(jLabel4)
                                .addComponent(jLabel6))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel7))))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Seed)
                            .addComponent(NumberOfPopulations)
                            .addComponent(NumberOfAgents)
                            .addComponent(NumberOfRounds)
                            .addComponent(ProbabilityChangeFactor)
                            .addComponent(NumberOfAgentsInPlay)
                            .addComponent(NumberOfImitators)
                            .addComponent(ImitationRounds)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(26, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3))
                        .addGap(113, 113, 113)))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(32, 32, 32)
                        .addComponent(jButton2))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(18, 18, 18)
                        .addComponent(NumberOfRuns, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(44, 44, 44))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Seed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NumberOfPopulations, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NumberOfAgents, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NumberOfAgentsInPlay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NumberOfImitators, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ImitationRounds, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NumberOfRounds, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8)
                .addContainerGap(17, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NumberOfRuns, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(ProbabilityChangeFactor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SeedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SeedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SeedActionPerformed

    private void NumberOfAgentsInPlayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NumberOfAgentsInPlayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NumberOfAgentsInPlayActionPerformed
   
    
 /**
 * The GUI button to start the Java Program. 
 * The program expects 9 input numbers, the value after the equal sign is the default value. 
 * The variables are explained in the class RunABS <br>
 *      int seed = 0; <br>
 *      int NumberOfPopulations = 1; <br>
 *      int NumberOfAgents = 99; <br>
 *      int NumberOfAgentsInPlay = 99; <br>
 *      int NumberOfImitators = 3; <br>
 *      int ImitationRounds = 3; <br>
 *      int NumberOfRounds = 10000; <br>
 *      double ProbabilityChangeFactor = 0.7; <br>
 *      int NumberOfRuns = 10 : The number of separate experiments  <br>
 * 
 * 
 * 
 * @author stathis
 */   
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

      //int NumberOfPopulations = NumberOfPopulations.getText();    
        
       int iseed = 0;
       int iNumberOfPopulations = 1; 
       int iNumberOfAgents = 99; 
       int iNumberOfAgentsInPlay = 99;
       int iNumberOfImitators = 3;
       int iImitationRounds = 3;
       int iNumberOfRounds = 10000;
       double iProbabilityChangeFactor = 0.7;
       int iNumberOfRuns = 10;
       boolean Run = true;
        
       try {
         iseed = Integer.parseInt(Seed.getText());
       } 
       catch (NumberFormatException e) {
                System.err.println("Argument: " + Seed.getText() + " must be an integer.");
                Run = false;
       } 
       
       try {
          iNumberOfPopulations = Integer.parseInt(NumberOfPopulations.getText());
          if(iNumberOfPopulations != 0 && (iNumberOfPopulations % 2 != 0) ){
               //NumberOfPopulations = args[1];
          }else{
                System.err.println("Argument: " + NumberOfPopulations.getText() + " must be an ODD integer greater of equal to one. ");
                Run = false;
          }
       }catch (NumberFormatException e) {
                System.err.println("Argument: " +  NumberOfPopulations.getText() + " must be an integer.");
                Run = false;
       }
       
       try {
           iNumberOfAgents =  Integer.parseInt(NumberOfAgents.getText());
          if(iNumberOfAgents != 0 && (iNumberOfAgents % 2 != 0) ){
                  //NumberOfAgents = args[2];
           }else{
             System.err.println("Argument: " + NumberOfAgents.getText() + " must be an ODD integer greater of equal to one. ");
             Run = false;
                //System.exit(1);
           }
               
        }catch (NumberFormatException e) {
               System.err.println("Argument: " + NumberOfAgents.getText() + " must be an integer.");
               Run = false;
        }
       
        try {
                iNumberOfAgentsInPlay =  Integer.parseInt(NumberOfAgentsInPlay.getText());
               if(iNumberOfAgentsInPlay != 0 && (iNumberOfAgentsInPlay % 2 != 0) ){
                  //NumberOfAgents = args[2];
               }else{
                System.err.println("Argument: " + NumberOfAgentsInPlay.getText() + " must be an ODD integer greater of equal to one. ");
                Run = false;
                //System.exit(1);
               }
               
            }catch (NumberFormatException e) {
               System.err.println("Argument: " + NumberOfAgentsInPlay.getText() + " must be an integer.");
               Run = false;
            } 
             
         try {
                iNumberOfImitators =  Integer.parseInt(NumberOfImitators.getText());
               if(iNumberOfImitators != 0 ){
                  //NumberOfAgents = args[2];
               }else{
                System.err.println("Argument: " + NumberOfImitators.getText() + " must be an integer greater of equal to one. ");
                Run = false;
                //System.exit(1);
               }
               
            }catch (NumberFormatException e) {
               System.err.println("Argument: " +  NumberOfImitators.getText() + " must be an integer.");
               Run = false;
            } 
            
           try {
               iImitationRounds =  Integer.parseInt(ImitationRounds.getText());
               if(iImitationRounds != 0 ){
                  //NumberOfAgents = args[2];
               }else{
                System.err.println("Argument: " + ImitationRounds.getText() + " must be an integer greater to zero and less than the total rounds of the Game. ");
                //System.exit(1);
                Run = false;
               }
               
            }catch (NumberFormatException e) {
               System.err.println("Argument: " + ImitationRounds.getText() + " must be an integer.");
               Run = false;
            } 
            
            try {
                iNumberOfRounds =  Integer.parseInt(NumberOfRounds.getText());
               if(iNumberOfRounds != 0 ){
                  //NumberOfAgents = args[2];
               }else{
                System.err.println("Argument: " + NumberOfRounds.getText() + " must be an integer greater than zero");
                //System.exit(1);
                Run = false;
               }
               
            }catch (NumberFormatException e) {
               System.err.println("Argument" + NumberOfRounds.getText() + " must be an integer.");
               Run = false;
            } 
            
            try {
                iProbabilityChangeFactor =  Double.parseDouble(ProbabilityChangeFactor.getText());
               if(iProbabilityChangeFactor != 0 && iProbabilityChangeFactor <= 1 ){
                  //NumberOfAgents = args[2];
               }else{
                System.err.println("Argument: " + ProbabilityChangeFactor.getText() + " must be an double greater than zero and less than one");
                //System.exit(1);
                Run = false;
               }
               
            }catch (NumberFormatException e) {
               System.err.println("Argument: " + ProbabilityChangeFactor.getText() + " must be an double.");
               Run = false;
            } 
            
            try {
                iNumberOfRuns =  Integer.parseInt(NumberOfRuns.getText());
               if(iNumberOfRuns != 0 ){
                  //NumberOfAgents = args[2];
               }else{
                System.err.println("Argument: " + NumberOfRuns.getText()  + " must be an integer greater than zero");
                //System.exit(1);
                Run = false;
               }
               
            }catch (NumberFormatException e) {
               System.err.println("Argument: " + NumberOfRuns.getText() + " must be an integer.");
               Run = false;
            }
        
             RunABS go = new RunABS();
             if(Run == true){
                 
                for(int iter = 0; iter < iNumberOfRuns; iter++){ 
                        System.out.println("Starting Experiment: " + iter); 
                        go.run(iter + iseed, 
           iNumberOfPopulations, 
           iNumberOfAgents, 
           iNumberOfAgentsInPlay,
           iNumberOfImitators,
           iImitationRounds,
           iNumberOfRounds,
           iProbabilityChangeFactor);

              }
            }
            System.out.println("Done!"); 
       
        
                  // PrintWriter writersum = null;
        //try {
            //RunABS go = new RunABS();
          
        //    Logger.getLogger(RunSimulation.class.getName()).log(Level.SEVERE, null, ex);
        //} catch (UnsupportedEncodingException ex) {
        //    Logger.getLogger(RunSimulation.class.getName()).log(Level.SEVERE, null, ex);
        //} finally {
        //    writersum.close();
       
        
      
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
        System.exit(0);
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MGJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MGJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MGJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MGJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new MGJFrame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ImitationRounds;
    private javax.swing.JTextField NumberOfAgents;
    private javax.swing.JTextField NumberOfAgentsInPlay;
    private javax.swing.JTextField NumberOfImitators;
    private javax.swing.JTextField NumberOfPopulations;
    private javax.swing.JTextField NumberOfRounds;
    private javax.swing.JTextField NumberOfRuns;
    private javax.swing.JTextField ProbabilityChangeFactor;
    private javax.swing.JTextField Seed;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
